// GENERATED by tool/generate_unified_countries.dart — do not edit by hand.

/// Bundled countries supported by unified phone fields and pickers.
enum UnifiedCountry {
  /// Andorra (`+376`).
  ad('AD', 'Andorra', '+376'),
  /// United Arab Emirates (`+971`).
  ae('AE', 'United Arab Emirates', '+971'),
  /// Afghanistan (`+93`).
  af('AF', 'Afghanistan', '+93'),
  /// Antigua and Barbuda (`+1`).
  ag('AG', 'Antigua and Barbuda', '+1'),
  /// Anguilla (`+1`).
  ai('AI', 'Anguilla', '+1'),
  /// Albania (`+355`).
  al('AL', 'Albania', '+355'),
  /// Armenia (`+374`).
  am('AM', 'Armenia', '+374'),
  /// Angola (`+244`).
  ao('AO', 'Angola', '+244'),
  /// Antarctica (`+672`).
  aq('AQ', 'Antarctica', '+672'),
  /// Argentina (`+54`).
  ar('AR', 'Argentina', '+54'),
  /// American Samoa (`+1`).
  countryAS('AS', 'American Samoa', '+1'),
  /// Austria (`+43`).
  at('AT', 'Austria', '+43'),
  /// Australia (`+61`).
  au('AU', 'Australia', '+61'),
  /// Aruba (`+297`).
  aw('AW', 'Aruba', '+297'),
  /// Aland Islands (`+358`).
  ax('AX', 'Aland Islands', '+358'),
  /// Azerbaijan (`+994`).
  az('AZ', 'Azerbaijan', '+994'),
  /// Bosnia and Herzegovina (`+387`).
  ba('BA', 'Bosnia and Herzegovina', '+387'),
  /// Barbados (`+1`).
  bb('BB', 'Barbados', '+1'),
  /// Bangladesh (`+880`).
  bd('BD', 'Bangladesh', '+880'),
  /// Belgium (`+32`).
  be('BE', 'Belgium', '+32'),
  /// Burkina Faso (`+226`).
  bf('BF', 'Burkina Faso', '+226'),
  /// Bulgaria (`+359`).
  bg('BG', 'Bulgaria', '+359'),
  /// Bahrain (`+973`).
  bh('BH', 'Bahrain', '+973'),
  /// Burundi (`+257`).
  bi('BI', 'Burundi', '+257'),
  /// Benin (`+229`).
  bj('BJ', 'Benin', '+229'),
  /// Saint-Barthelemy (`+590`).
  bl('BL', 'Saint-Barthelemy', '+590'),
  /// Bermuda (`+1`).
  bm('BM', 'Bermuda', '+1'),
  /// Brunei (`+673`).
  bn('BN', 'Brunei', '+673'),
  /// Bolivia (`+591`).
  bo('BO', 'Bolivia', '+591'),
  /// Bonaire, Sint Eustatius and Saba (`+599`).
  bq('BQ', 'Bonaire, Sint Eustatius and Saba', '+599'),
  /// Brazil (`+55`).
  br('BR', 'Brazil', '+55'),
  /// The Bahamas (`+1`).
  bs('BS', 'The Bahamas', '+1'),
  /// Bhutan (`+975`).
  bt('BT', 'Bhutan', '+975'),
  /// Bouvet Island (`+0055`).
  bv('BV', 'Bouvet Island', '+0055'),
  /// Botswana (`+267`).
  bw('BW', 'Botswana', '+267'),
  /// Belarus (`+375`).
  by('BY', 'Belarus', '+375'),
  /// Belize (`+501`).
  bz('BZ', 'Belize', '+501'),
  /// Canada (`+1`).
  ca('CA', 'Canada', '+1'),
  /// Cocos (Keeling) Islands (`+61`).
  cc('CC', 'Cocos (Keeling) Islands', '+61'),
  /// Democratic Republic of the Congo (`+243`).
  cd('CD', 'Democratic Republic of the Congo', '+243'),
  /// Central African Republic (`+236`).
  cf('CF', 'Central African Republic', '+236'),
  /// Congo (`+242`).
  cg('CG', 'Congo', '+242'),
  /// Switzerland (`+41`).
  ch('CH', 'Switzerland', '+41'),
  /// Ivory Coast (`+225`).
  ci('CI', 'Ivory Coast', '+225'),
  /// Cook Islands (`+682`).
  ck('CK', 'Cook Islands', '+682'),
  /// Chile (`+56`).
  cl('CL', 'Chile', '+56'),
  /// Cameroon (`+237`).
  cm('CM', 'Cameroon', '+237'),
  /// China (`+86`).
  cn('CN', 'China', '+86'),
  /// Colombia (`+57`).
  co('CO', 'Colombia', '+57'),
  /// Costa Rica (`+506`).
  cr('CR', 'Costa Rica', '+506'),
  /// Cuba (`+53`).
  cu('CU', 'Cuba', '+53'),
  /// Cape Verde (`+238`).
  cv('CV', 'Cape Verde', '+238'),
  /// Curaçao (`+599`).
  cw('CW', 'Curaçao', '+599'),
  /// Christmas Island (`+61`).
  cx('CX', 'Christmas Island', '+61'),
  /// Cyprus (`+357`).
  cy('CY', 'Cyprus', '+357'),
  /// Czech Republic (`+420`).
  cz('CZ', 'Czech Republic', '+420'),
  /// Germany (`+49`).
  de('DE', 'Germany', '+49'),
  /// Djibouti (`+253`).
  dj('DJ', 'Djibouti', '+253'),
  /// Denmark (`+45`).
  dk('DK', 'Denmark', '+45'),
  /// Dominica (`+1`).
  dm('DM', 'Dominica', '+1'),
  /// Dominican Republic (`+1`).
  countryDO('DO', 'Dominican Republic', '+1'),
  /// Algeria (`+213`).
  dz('DZ', 'Algeria', '+213'),
  /// Ecuador (`+593`).
  ec('EC', 'Ecuador', '+593'),
  /// Estonia (`+372`).
  ee('EE', 'Estonia', '+372'),
  /// Egypt (`+20`).
  eg('EG', 'Egypt', '+20'),
  /// Western Sahara (`+212`).
  eh('EH', 'Western Sahara', '+212'),
  /// Eritrea (`+291`).
  er('ER', 'Eritrea', '+291'),
  /// Spain (`+34`).
  es('ES', 'Spain', '+34'),
  /// Ethiopia (`+251`).
  et('ET', 'Ethiopia', '+251'),
  /// Finland (`+358`).
  fi('FI', 'Finland', '+358'),
  /// Fiji Islands (`+679`).
  fj('FJ', 'Fiji Islands', '+679'),
  /// Falkland Islands (`+500`).
  fk('FK', 'Falkland Islands', '+500'),
  /// Micronesia (`+691`).
  fm('FM', 'Micronesia', '+691'),
  /// Faroe Islands (`+298`).
  fo('FO', 'Faroe Islands', '+298'),
  /// France (`+33`).
  fr('FR', 'France', '+33'),
  /// Gabon (`+241`).
  ga('GA', 'Gabon', '+241'),
  /// United Kingdom (`+44`).
  gb('GB', 'United Kingdom', '+44'),
  /// Grenada (`+1`).
  gd('GD', 'Grenada', '+1'),
  /// Georgia (`+995`).
  ge('GE', 'Georgia', '+995'),
  /// French Guiana (`+594`).
  gf('GF', 'French Guiana', '+594'),
  /// Guernsey (`+44`).
  gg('GG', 'Guernsey', '+44'),
  /// Ghana (`+233`).
  gh('GH', 'Ghana', '+233'),
  /// Gibraltar (`+350`).
  gi('GI', 'Gibraltar', '+350'),
  /// Greenland (`+299`).
  gl('GL', 'Greenland', '+299'),
  /// The Gambia (`+220`).
  gm('GM', 'The Gambia', '+220'),
  /// Guinea (`+224`).
  gn('GN', 'Guinea', '+224'),
  /// Guadeloupe (`+590`).
  gp('GP', 'Guadeloupe', '+590'),
  /// Equatorial Guinea (`+240`).
  gq('GQ', 'Equatorial Guinea', '+240'),
  /// Greece (`+30`).
  gr('GR', 'Greece', '+30'),
  /// South Georgia (`+500`).
  gs('GS', 'South Georgia', '+500'),
  /// Guatemala (`+502`).
  gt('GT', 'Guatemala', '+502'),
  /// Guam (`+1`).
  gu('GU', 'Guam', '+1'),
  /// Guinea-Bissau (`+245`).
  gw('GW', 'Guinea-Bissau', '+245'),
  /// Guyana (`+592`).
  gy('GY', 'Guyana', '+592'),
  /// Hong Kong S.A.R. (`+852`).
  hk('HK', 'Hong Kong S.A.R.', '+852'),
  /// Heard Island and McDonald Islands (`+672`).
  hm('HM', 'Heard Island and McDonald Islands', '+672'),
  /// Honduras (`+504`).
  hn('HN', 'Honduras', '+504'),
  /// Croatia (`+385`).
  hr('HR', 'Croatia', '+385'),
  /// Haiti (`+509`).
  ht('HT', 'Haiti', '+509'),
  /// Hungary (`+36`).
  hu('HU', 'Hungary', '+36'),
  /// Indonesia (`+62`).
  id('ID', 'Indonesia', '+62'),
  /// Ireland (`+353`).
  ie('IE', 'Ireland', '+353'),
  /// Israel (`+972`).
  il('IL', 'Israel', '+972'),
  /// Man (Isle of) (`+44`).
  im('IM', 'Man (Isle of)', '+44'),
  /// India (`+91`).
  countryIN('IN', 'India', '+91'),
  /// British Indian Ocean Territory (`+246`).
  io('IO', 'British Indian Ocean Territory', '+246'),
  /// Iraq (`+964`).
  iq('IQ', 'Iraq', '+964'),
  /// Iran (`+98`).
  ir('IR', 'Iran', '+98'),
  /// Iceland (`+354`).
  countryIS('IS', 'Iceland', '+354'),
  /// Italy (`+39`).
  it('IT', 'Italy', '+39'),
  /// Jersey (`+44`).
  je('JE', 'Jersey', '+44'),
  /// Jamaica (`+1`).
  jm('JM', 'Jamaica', '+1'),
  /// Jordan (`+962`).
  jo('JO', 'Jordan', '+962'),
  /// Japan (`+81`).
  jp('JP', 'Japan', '+81'),
  /// Kenya (`+254`).
  ke('KE', 'Kenya', '+254'),
  /// Kyrgyzstan (`+996`).
  kg('KG', 'Kyrgyzstan', '+996'),
  /// Cambodia (`+855`).
  kh('KH', 'Cambodia', '+855'),
  /// Kiribati (`+686`).
  ki('KI', 'Kiribati', '+686'),
  /// Comoros (`+269`).
  km('KM', 'Comoros', '+269'),
  /// Saint Kitts and Nevis (`+1`).
  kn('KN', 'Saint Kitts and Nevis', '+1'),
  /// North Korea (`+850`).
  kp('KP', 'North Korea', '+850'),
  /// South Korea (`+82`).
  kr('KR', 'South Korea', '+82'),
  /// Kuwait (`+965`).
  kw('KW', 'Kuwait', '+965'),
  /// Cayman Islands (`+1`).
  ky('KY', 'Cayman Islands', '+1'),
  /// Kazakhstan (`+7`).
  kz('KZ', 'Kazakhstan', '+7'),
  /// Laos (`+856`).
  la('LA', 'Laos', '+856'),
  /// Lebanon (`+961`).
  lb('LB', 'Lebanon', '+961'),
  /// Saint Lucia (`+1`).
  lc('LC', 'Saint Lucia', '+1'),
  /// Liechtenstein (`+423`).
  li('LI', 'Liechtenstein', '+423'),
  /// Sri Lanka (`+94`).
  lk('LK', 'Sri Lanka', '+94'),
  /// Liberia (`+231`).
  lr('LR', 'Liberia', '+231'),
  /// Lesotho (`+266`).
  ls('LS', 'Lesotho', '+266'),
  /// Lithuania (`+370`).
  lt('LT', 'Lithuania', '+370'),
  /// Luxembourg (`+352`).
  lu('LU', 'Luxembourg', '+352'),
  /// Latvia (`+371`).
  lv('LV', 'Latvia', '+371'),
  /// Libya (`+218`).
  ly('LY', 'Libya', '+218'),
  /// Morocco (`+212`).
  ma('MA', 'Morocco', '+212'),
  /// Monaco (`+377`).
  mc('MC', 'Monaco', '+377'),
  /// Moldova (`+373`).
  md('MD', 'Moldova', '+373'),
  /// Montenegro (`+382`).
  me('ME', 'Montenegro', '+382'),
  /// Saint-Martin (French part) (`+590`).
  mf('MF', 'Saint-Martin (French part)', '+590'),
  /// Madagascar (`+261`).
  mg('MG', 'Madagascar', '+261'),
  /// Marshall Islands (`+692`).
  mh('MH', 'Marshall Islands', '+692'),
  /// North Macedonia (`+389`).
  mk('MK', 'North Macedonia', '+389'),
  /// Mali (`+223`).
  ml('ML', 'Mali', '+223'),
  /// Myanmar (`+95`).
  mm('MM', 'Myanmar', '+95'),
  /// Mongolia (`+976`).
  mn('MN', 'Mongolia', '+976'),
  /// Macau S.A.R. (`+853`).
  mo('MO', 'Macau S.A.R.', '+853'),
  /// Northern Mariana Islands (`+1`).
  mp('MP', 'Northern Mariana Islands', '+1'),
  /// Martinique (`+596`).
  mq('MQ', 'Martinique', '+596'),
  /// Mauritania (`+222`).
  mr('MR', 'Mauritania', '+222'),
  /// Montserrat (`+1`).
  ms('MS', 'Montserrat', '+1'),
  /// Malta (`+356`).
  mt('MT', 'Malta', '+356'),
  /// Mauritius (`+230`).
  mu('MU', 'Mauritius', '+230'),
  /// Maldives (`+960`).
  mv('MV', 'Maldives', '+960'),
  /// Malawi (`+265`).
  mw('MW', 'Malawi', '+265'),
  /// Mexico (`+52`).
  mx('MX', 'Mexico', '+52'),
  /// Malaysia (`+60`).
  my('MY', 'Malaysia', '+60'),
  /// Mozambique (`+258`).
  mz('MZ', 'Mozambique', '+258'),
  /// Namibia (`+264`).
  na('NA', 'Namibia', '+264'),
  /// New Caledonia (`+687`).
  nc('NC', 'New Caledonia', '+687'),
  /// Niger (`+227`).
  ne('NE', 'Niger', '+227'),
  /// Norfolk Island (`+672`).
  nf('NF', 'Norfolk Island', '+672'),
  /// Nigeria (`+234`).
  ng('NG', 'Nigeria', '+234'),
  /// Nicaragua (`+505`).
  ni('NI', 'Nicaragua', '+505'),
  /// Netherlands (`+31`).
  nl('NL', 'Netherlands', '+31'),
  /// Norway (`+47`).
  no('NO', 'Norway', '+47'),
  /// Nepal (`+977`).
  np('NP', 'Nepal', '+977'),
  /// Nauru (`+674`).
  nr('NR', 'Nauru', '+674'),
  /// Niue (`+683`).
  nu('NU', 'Niue', '+683'),
  /// New Zealand (`+64`).
  nz('NZ', 'New Zealand', '+64'),
  /// Oman (`+968`).
  om('OM', 'Oman', '+968'),
  /// Panama (`+507`).
  pa('PA', 'Panama', '+507'),
  /// Peru (`+51`).
  pe('PE', 'Peru', '+51'),
  /// French Polynesia (`+689`).
  pf('PF', 'French Polynesia', '+689'),
  /// Papua New Guinea (`+675`).
  pg('PG', 'Papua New Guinea', '+675'),
  /// Philippines (`+63`).
  ph('PH', 'Philippines', '+63'),
  /// Pakistan (`+92`).
  pk('PK', 'Pakistan', '+92'),
  /// Poland (`+48`).
  pl('PL', 'Poland', '+48'),
  /// Saint Pierre and Miquelon (`+508`).
  pm('PM', 'Saint Pierre and Miquelon', '+508'),
  /// Pitcairn Island (`+870`).
  pn('PN', 'Pitcairn Island', '+870'),
  /// Puerto Rico (`+1`).
  pr('PR', 'Puerto Rico', '+1'),
  /// Palestinian Territory Occupied (`+970`).
  ps('PS', 'Palestinian Territory Occupied', '+970'),
  /// Portugal (`+351`).
  pt('PT', 'Portugal', '+351'),
  /// Palau (`+680`).
  pw('PW', 'Palau', '+680'),
  /// Paraguay (`+595`).
  py('PY', 'Paraguay', '+595'),
  /// Qatar (`+974`).
  qa('QA', 'Qatar', '+974'),
  /// Reunion (`+262`).
  re('RE', 'Reunion', '+262'),
  /// Romania (`+40`).
  ro('RO', 'Romania', '+40'),
  /// Serbia (`+381`).
  rs('RS', 'Serbia', '+381'),
  /// Russia (`+7`).
  ru('RU', 'Russia', '+7'),
  /// Rwanda (`+250`).
  rw('RW', 'Rwanda', '+250'),
  /// Saudi Arabia (`+966`).
  sa('SA', 'Saudi Arabia', '+966'),
  /// Solomon Islands (`+677`).
  sb('SB', 'Solomon Islands', '+677'),
  /// Seychelles (`+248`).
  sc('SC', 'Seychelles', '+248'),
  /// Sudan (`+249`).
  sd('SD', 'Sudan', '+249'),
  /// Sweden (`+46`).
  se('SE', 'Sweden', '+46'),
  /// Singapore (`+65`).
  sg('SG', 'Singapore', '+65'),
  /// Saint Helena (`+290`).
  sh('SH', 'Saint Helena', '+290'),
  /// Slovenia (`+386`).
  si('SI', 'Slovenia', '+386'),
  /// Svalbard and Jan Mayen Islands (`+47`).
  sj('SJ', 'Svalbard and Jan Mayen Islands', '+47'),
  /// Slovakia (`+421`).
  sk('SK', 'Slovakia', '+421'),
  /// Sierra Leone (`+232`).
  sl('SL', 'Sierra Leone', '+232'),
  /// San Marino (`+378`).
  sm('SM', 'San Marino', '+378'),
  /// Senegal (`+221`).
  sn('SN', 'Senegal', '+221'),
  /// Somalia (`+252`).
  so('SO', 'Somalia', '+252'),
  /// Suriname (`+597`).
  sr('SR', 'Suriname', '+597'),
  /// South Sudan (`+211`).
  ss('SS', 'South Sudan', '+211'),
  /// Sao Tome and Principe (`+239`).
  st('ST', 'Sao Tome and Principe', '+239'),
  /// El Salvador (`+503`).
  sv('SV', 'El Salvador', '+503'),
  /// Sint Maarten (Dutch part) (`+1721`).
  sx('SX', 'Sint Maarten (Dutch part)', '+1721'),
  /// Syria (`+963`).
  sy('SY', 'Syria', '+963'),
  /// Eswatini (`+268`).
  sz('SZ', 'Eswatini', '+268'),
  /// Turks and Caicos Islands (`+1`).
  tc('TC', 'Turks and Caicos Islands', '+1'),
  /// Chad (`+235`).
  td('TD', 'Chad', '+235'),
  /// French Southern Territories (`+262`).
  tf('TF', 'French Southern Territories', '+262'),
  /// Togo (`+228`).
  tg('TG', 'Togo', '+228'),
  /// Thailand (`+66`).
  th('TH', 'Thailand', '+66'),
  /// Tajikistan (`+992`).
  tj('TJ', 'Tajikistan', '+992'),
  /// Tokelau (`+690`).
  tk('TK', 'Tokelau', '+690'),
  /// Timor-Leste (`+670`).
  tl('TL', 'Timor-Leste', '+670'),
  /// Turkmenistan (`+993`).
  tm('TM', 'Turkmenistan', '+993'),
  /// Tunisia (`+216`).
  tn('TN', 'Tunisia', '+216'),
  /// Tonga (`+676`).
  to('TO', 'Tonga', '+676'),
  /// Turkey (`+90`).
  tr('TR', 'Turkey', '+90'),
  /// Trinidad and Tobago (`+1`).
  tt('TT', 'Trinidad and Tobago', '+1'),
  /// Tuvalu (`+688`).
  tv('TV', 'Tuvalu', '+688'),
  /// Taiwan (`+886`).
  tw('TW', 'Taiwan', '+886'),
  /// Tanzania (`+255`).
  tz('TZ', 'Tanzania', '+255'),
  /// Ukraine (`+380`).
  ua('UA', 'Ukraine', '+380'),
  /// Uganda (`+256`).
  ug('UG', 'Uganda', '+256'),
  /// United States Minor Outlying Islands (`+1`).
  um('UM', 'United States Minor Outlying Islands', '+1'),
  /// United States (`+1`).
  us('US', 'United States', '+1'),
  /// Uruguay (`+598`).
  uy('UY', 'Uruguay', '+598'),
  /// Uzbekistan (`+998`).
  uz('UZ', 'Uzbekistan', '+998'),
  /// Vatican City State (Holy See) (`+379`).
  va('VA', 'Vatican City State (Holy See)', '+379'),
  /// Saint Vincent and the Grenadines (`+1`).
  vc('VC', 'Saint Vincent and the Grenadines', '+1'),
  /// Venezuela (`+58`).
  ve('VE', 'Venezuela', '+58'),
  /// Virgin Islands (British) (`+1`).
  vg('VG', 'Virgin Islands (British)', '+1'),
  /// Virgin Islands (US) (`+1`).
  vi('VI', 'Virgin Islands (US)', '+1'),
  /// Vietnam (`+84`).
  vn('VN', 'Vietnam', '+84'),
  /// Vanuatu (`+678`).
  vu('VU', 'Vanuatu', '+678'),
  /// Wallis and Futuna Islands (`+681`).
  wf('WF', 'Wallis and Futuna Islands', '+681'),
  /// Samoa (`+685`).
  ws('WS', 'Samoa', '+685'),
  /// Kosovo (`+383`).
  xk('XK', 'Kosovo', '+383'),
  /// Yemen (`+967`).
  ye('YE', 'Yemen', '+967'),
  /// Mayotte (`+262`).
  yt('YT', 'Mayotte', '+262'),
  /// South Africa (`+27`).
  za('ZA', 'South Africa', '+27'),
  /// Zambia (`+260`).
  zm('ZM', 'Zambia', '+260'),
  /// Zimbabwe (`+263`).
  zw('ZW', 'Zimbabwe', '+263'),
;

  /// Creates a country entry.
  const UnifiedCountry(this.isoCode, this.name, this.dialCode);

  /// ISO 3166-1 alpha-2 (e.g. `US`, `IR`).
  final String isoCode;

  /// Display name (e.g. `United States`).
  final String name;

  /// ITU dial code including `+` (e.g. `+1`, `+98`).
  final String dialCode;
}
