// ignore_for_file: avoid_print

import 'dart:convert';
import 'dart:io';

const _dartKeywords = <String>{
  'abstract',
  'as',
  'assert',
  'async',
  'await',
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'covariant',
  'default',
  'deferred',
  'do',
  'dynamic',
  'else',
  'enum',
  'export',
  'extends',
  'extension',
  'external',
  'factory',
  'false',
  'final',
  'finally',
  'for',
  'function',
  'get',
  'hide',
  'if',
  'implements',
  'import',
  'in',
  'interface',
  'is',
  'late',
  'library',
  'mixin',
  'new',
  'null',
  'on',
  'operator',
  'part',
  'required',
  'rethrow',
  'return',
  'sealed',
  'set',
  'show',
  'static',
  'super',
  'switch',
  'sync',
  'this',
  'throw',
  'true',
  'try',
  'typedef',
  'var',
  'void',
  'when',
  'while',
  'with',
  'yield',
};

String escapeDart(String s) => s
    .replaceAll(r'\', r'\\')
    .replaceAll("'", r"\'");

String enumMemberName(String iso2) {
  final lower = iso2.toLowerCase();
  if (_dartKeywords.contains(lower) || !RegExp(r'^[a-z][a-z0-9]*$').hasMatch(lower)) {
    return 'country${iso2.toUpperCase()}';
  }
  return lower;
}

void main() {
  final root = Directory.current.path.endsWith('tool')
      ? Directory.current.parent
      : Directory.current;
  final jsonFile = File('${root.path}/tool/countries.json');
  if (!jsonFile.existsSync()) {
    stderr.writeln('Missing ${jsonFile.path}. Download countries.json first.');
    exit(1);
  }

  final list = jsonDecode(jsonFile.readAsStringSync()) as List<dynamic>;
  final entries = <({String iso, String name, String dial})>[];

  for (final raw in list) {
    final map = raw as Map<String, dynamic>;
    final iso = (map['iso2'] as String?)?.trim();
    final name = (map['name'] as String?)?.trim();
    final phone = (map['phonecode'] as String?)?.trim();
    if (iso == null || iso.length != 2 || name == null || name.isEmpty) {
      continue;
    }
    if (phone == null || phone.isEmpty) continue;
    final dial = phone.startsWith('+') ? phone : '+$phone';
    entries.add((iso: iso.toUpperCase(), name: name, dial: dial));
  }

  entries.sort((a, b) => a.iso.compareTo(b.iso));

  final usedNames = <String>{};
  final buffer = StringBuffer()
    ..writeln('// GENERATED by tool/generate_unified_countries.dart — do not edit by hand.')
    ..writeln()
    ..writeln('/// Bundled countries supported by unified phone fields and pickers.')
    ..writeln('enum UnifiedCountry {');

  for (final e in entries) {
    var member = enumMemberName(e.iso);
    var suffix = 0;
    while (usedNames.contains(member)) {
      suffix++;
      member = '${enumMemberName(e.iso)}$suffix';
    }
    usedNames.add(member);
    buffer.writeln(
      "  /// ${escapeDart(e.name)} (`${escapeDart(e.dial)}`).",
    );
    buffer.writeln(
      "  $member('${e.iso}', '${escapeDart(e.name)}', '${escapeDart(e.dial)}'),",
    );
  }

  buffer.writeln(';');
  buffer.writeln();
  buffer.writeln('  /// Creates a country entry.');
  buffer.writeln('  const UnifiedCountry(this.isoCode, this.name, this.dialCode);');
  buffer.writeln();
  buffer.writeln('  /// ISO 3166-1 alpha-2 (e.g. `US`, `IR`).');
  buffer.writeln('  final String isoCode;');
  buffer.writeln();
  buffer.writeln('  /// Display name (e.g. `United States`).');
  buffer.writeln('  final String name;');
  buffer.writeln();
  buffer.writeln('  /// ITU dial code including `+` (e.g. `+1`, `+98`).');
  buffer.writeln('  final String dialCode;');
  buffer.writeln('}');

  final out = File('${root.path}/lib/src/phone/unified_country_enum.dart');
  out.writeAsStringSync(buffer.toString());
  print('Wrote ${entries.length} countries to ${out.path}');
}
